export enum AuthConstants {
  SET_AUTHORIZATION_TOKEN = '@@Auth/SET_AUTHORIZATION_TOKEN',
  SET_USER = '@@Auth/SET_USER',
  LOGIN_ASYNC = '@@Auth/LOGIN_ASYNC',
  LOGOUT_ASYNC = '@@Auth/LOGOUT_ASYNC',
  CHECK_IS_AUTHENTICATED_ASYNC = '@@Auth/CHECK_IS_AUTHENTICATED_ASYNC',
}
