version: '3'

services:
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - blue_nebula_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  blue_nebula_data:
