version: '3'

services:
  postgres:
    image: 'postgres'
    env_file:
      - .env
    volumes:
      - scraper_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  scraper_data:
