export enum ControlConstants {
  SET_CONTROL_ENTITIES = '@@ControlConstants/SET_CONTROL_ENTITIES',
  REMOVE_CONTROL_ENTITY = '@@ControlConstants/REMOVE_CONTROL_ENTITY',
  CLEAR_ALL_CONTROL_ENTITIES = '@@ControlConstants/CLEAR_ALL_CONTROL_ENTITIES',
}
