export enum BluetoothConstants {
  SET_BLE_MANAGER = '@@BLUETOOTH/SET_BLE_MANAGER',
  SET_BLE_MANAGER_STATE = '@@BLUETOOTH/SET_BLE_MANAGER_STATE',
  SET_IS_BLE_RPI_DEVICE_CONNECTED = '@@BLUETOOTH/SET_IS_BLE_RPI_DEVICE_CONNECTED',
  SET_BLE_RPI_DEVICE_SERVICES_CHARACTERISTICS = '@@BLUETOOTH/SET_BLE_RPI_DEVICE_SERVICES_CHARACTERISTICS',
  CONNECT_ASYNC = '@@BLUETOOTH/CONNECT_ASYNC',
  CANCEL_CONNECT = '@@BLUETOOTH/CANCEL_CONNECT',
  SET_IS_SCANNING_AND_CONNECTING = '@@BLUETOOTH/SET_IS_SCANNING_AND_CONNECTING',
  READ_CHARACTERISTIC_VALUE_ASYNC = '@@BLUETOOTH/READ_CHARACTERISTIC_VALUE_ASYNC',
  WRITE_CHARACTERISTIC_VALUE_ASYNC = '@@BLUETOOTH/WRITE_CHARACTERISTIC_VALUE_ASYNC',
}
