export enum ApplicationConstants {
  SET_IS_LOADING = '@@Application/SET_IS_LOADING',
  SET_APPLICATION_ALERT = '@@Application/SET_APPLICATION_ALERT',
  SET_APPLICATION_MODE = '@@Application/SET_APPLICATION_MODE',
  SET_FOCUSED_MICRO_APP_HEADERS = '@@Application/SET_FOCUSED_MICRO_APP_HEADERS',
  SET_SHOULD_FETCH_MICRO_APP = '@@Application/SET_SHOULD_FETCH_MICRO_APP',
  SET_SHOULD_FORCE_MICRO_APP_UPDATE = '@@Application/SET_SHOULD_FORCE_MICRO_APP_UPDATE',
}
