export enum ApplicationConstants {
  SET_IS_LOADING = '@@Application/SET_IS_LOADING',
  SET_APPLICATION_ERROR = '@@Application/SET_APPLICATION_ERROR',
  SET_APPLICATION_MODE = '@@Application/SET_APPLICATION_MODE',
  SET_FOCUSED_MICRO_APP_HEADERS = '@@Application/SET_FOCUSED_MICRO_APP_HEADERS',
  SET_SHOULD_FETCH_MICRO_APP = '@@Application/SET_SHOULD_FETCH_MICRO_APP',
}
